name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main  # Trigger the action on push to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Docker Hub username from GitHub secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Docker Hub password from GitHub secrets

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1  # Setup Docker Buildx for building multi-platform images

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} .  # Replace 'my-app' with your app's name
        docker tag ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/my-app:latest

    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}/my-app:latest
