name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - main 

jobs:
  runs-on: ubuntu-latest
  checkout-code:
    steps:
    - name: Checkout code
      uses: actions/checkout@v3 
  login-docker-hub:
    steps:
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  
        password: ${{ secrets.DOCKER_PASSWORD }}  
  build-and-push:
    steps:
    # Step 3: Set up Docker Buildx (this is useful for building multi-platform images)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2  # Use the latest version of setup-buildx-action

    # Step 4: Cache Docker layers to speed up the build process
    - name: Cache Docker layers
      uses: actions/cache@v3  # Update to actions/cache@v3 for the latest version
      with:
        path: ~/.cache/docker
        key: ${{ runner.os }}-docker-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-docker-

    # Step 5: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }} .  # Replace 'my-app' with your app's name
        docker tag ${{ secrets.DOCKER_USERNAME }}/user-service:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/user-service:latest

    # Step 6: Push Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}user-service:${{ github.sha }}
        docker push ${{ secrets.DOCKER_USERNAME }}user-service:latest
